package_assets: 	always
embed_assets: 		  	on
compress_assets: 		on
package_path: 			packages
javascript_compressor:  closure
javascripts:
  common:
    - public/javascripts/jquery-1.11.3.min.js
    - public/javascripts/counter.js
stylesheets:
  common:
    - public/stylesheets/*.css