<%= "package_assets:    always" %>
embed_assets:           on          # (on, off, datauri)
compress_assets:        on
package_path:           packages    # (defaults to assets)
javascript_compressor:  closure     # (yui, closure)

javascripts:
  common:    
    - public/javascripts/jquery-1.11.3.js     
    - public/javascripts/mainjs.js
stylesheets:
  common:    
    - public/stylesheets/*.css
  

  